import{S as p,i as f}from"./assets/vendor-0fc460d7.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&o(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function y(n){const t="44204846-4ec433e2c1cc73895dee1a984",a="https://pixabay.com/api/",o=new URLSearchParams({key:t,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(`${a}?${o}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}function g(n){const t=document.createDocumentFragment(),a=document.querySelector("ul.gallery");n.hits.forEach(e=>{t.appendChild(E(e.webformatURL,e.largeImageURL,e.tags,e.likes,e.views,e.comments,e.downloads))}),a.appendChild(t);var o=new p(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"});o.refresh()}function h(){const n=document.querySelector("ul.gallery");n.innerHTML=""}function E(n,t,a,o,e,r,s){const l=document.createElement("li");l.className="gallery-item";const m=document.createElement("div");m.className="gallery-div-up";const c=document.createElement("a");c.className="gallery-link",c.href=t;const i=document.createElement("img");i.className="gallery-image",i.src=n,i.alt=a,c.appendChild(i),m.appendChild(c);const u=document.createElement("div");return u.className="gallery-likes",u.innerHTML=`
    <ul>
        <li>Likes<br><span class="counter">${o}</span></li>
        <li>Views<br><span class="counter">${e}</span></li>
        <li>Comments<br><span class="counter">${r}</span></li>
        <li>Downloads<br><span class="counter">${s}</span></li>
    </ul>
    `,l.appendChild(m),l.appendChild(u),l}function d(n){f.error({title:"Error",message:n,position:"topRight"})}document.getElementById("search-form").addEventListener("submit",function(n){const t="Sorry, there are no images matching your search query. Please try again!";n.preventDefault();const a=document.getElementById("pixabay").value.trim();a===""?d(t):(document.getElementById("loading").style.display="block",h(),y(a).then(o=>{o.total!==0?g(o):d(t),document.getElementById("loading").style.display="none"}).catch(o=>d("Error")))});
//# sourceMappingURL=commonHelpers.js.map
