import{a as w,S as L,i as I}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();async function b(r,t=1,n=15){const a="44204846-4ec433e2c1cc73895dee1a984",e="https://pixabay.com/api/";return(await w.get(e,{params:{key:a,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:n,page:t}})).data}function v(r){const t=document.createDocumentFragment(),n=document.querySelector("ul.gallery");r.hits.forEach(e=>{t.appendChild(P(e.webformatURL,e.largeImageURL,e.tags,e.likes,e.views,e.comments,e.downloads))}),n.appendChild(t);var a=new L(".gallery a",{captions:!0,captionDelay:250,captionsData:"alt"});a.refresh()}function B(){const r=document.querySelector("ul.gallery");r.innerHTML=""}function P(r,t,n,a,e,o,l){const i=document.createElement("li");i.className="gallery-item";const y=document.createElement("div");y.className="gallery-div-up";const d=document.createElement("a");d.className="gallery-link",d.href=t;const m=document.createElement("img");m.className="gallery-image",m.src=r,m.alt=n,d.appendChild(m),y.appendChild(d);const g=document.createElement("div");return g.className="gallery-likes",g.innerHTML=`
    <ul>
        <li>Likes<br><span class="counter">${a}</span></li>
        <li>Views<br><span class="counter">${e}</span></li>
        <li>Comments<br><span class="counter">${o}</span></li>
        <li>Downloads<br><span class="counter">${l}</span></li>
    </ul>
    `,i.appendChild(y),i.appendChild(g),i}const h="Sorry, there are no images matching your search query. Please try again!";let s=1,f=15,u="";function c(r){I.error({title:"Error",message:r,position:"topRight"})}function p(r){document.getElementById(r).style.display="none"}function E(r){document.getElementById(r).style.display="block"}document.getElementById("search-form").addEventListener("submit",async r=>{if(r.preventDefault(),p("loadmore"),u=document.getElementById("pixabay").value.trim(),s=1,u==="")c(h);else{E("loading"),B();try{const t=await b(u,s,f);t.total!==0?(v(t),E("loadmore")):c(h),p("loading")}catch{c("Error")}}});document.getElementById("loadmore").addEventListener("click",async()=>{document.getElementById("loading").style.display="block",s+=1;function r(){let n=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({left:0,top:n.height*3.5,behavior:"smooth"})}try{const t=await b(u,s,f);v(t),r(),s*f>=t.totalHits&&(p("loadmore"),c("We're sorry, but you've reached the end of search results.")),p("loading")}catch{c("Error")}});
//# sourceMappingURL=commonHelpers.js.map
